# serverless.yml

service: fullstack-coding-challenge

custom:
  tableName: 'items-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["ItemsDynamoDBTable", "Arn" ] }
  environment:
    ITEMS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: handler.handler
    events:
      - http: ANY /
        cors: true
      - http: 'ANY {proxy+}'
        cors: true

resources:
  Resources:
    ItemsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: itemId
            AttributeType: S
        KeySchema:
          -
            AttributeName: itemId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}

package:
  patterns:
    - '!node_modules/**'
    - 'node_modules/cors/**'
    - 'node_modules/serverless-http/**'
    - 'node_modules/express/**'
    - 'node_modules/aws-sdk/**'
    - 'node_modules/body-parser/**'
    - 'node_modules/depd/**'
    - 'node_modules/debug/**'
    - 'node_modules/merge-descriptors/**'
    - 'node_modules/accepts/**'
    - 'node_modules/array-flatten/**'
    - 'node_modules/aws-sdk/**'
    - 'node_modules/base64-js/**'
    - 'node_modules/buffer/**'
    - 'node_modules/bytes/**'
    - 'node_modules/content-disposition/**'
    - 'node_modules/content-type/**'
    - 'node_modules/cookie/**'
    - 'node_modules/cookie-signature/**'
    - 'node_modules/debugdepd/**'
    - 'node_modules/destroy/**'
    - 'node_modules/ee-first/**'
    - 'node_modules/encodeurl/**'
    - 'node_modules/escape-html/**'
    - 'node_modules/etag/**'
    - 'node_modules/events/**'
    - 'node_modules/express/**'
    - 'node_modules/finalhandler/**'
    - 'node_modules/forwarded/**'
    - 'node_modules/fresh/**'
    - 'node_modules/http-errors/**'
    - 'node_modules/iconv-lite/**'
    - 'node_modules/ieee754/**'
    - 'node_modules/inherits/**'
    - 'node_modules/ipaddr.js/**'
    - 'node_modules/isarray/**'
    - 'node_modules/jmespath/**'
    - 'node_modules/media-typer/**'
    - 'node_modules/merge-descriptors/**'
    - 'node_modules/methods/**'
    - 'node_modules/mime/**'
    - 'node_modules/mime-db/**'
    - 'node_modules/mime-types/**'
    - 'node_modules/ms/**'
    - 'node_modules/negotiator/**'
    - 'node_modules/object-assign/**'
    - 'node_modules/on-finished/**'
    - 'node_modules/parseurl/**'
    - 'node_modules/path-to-regexp/**'
    - 'node_modules/proxy-addr/**'
    - 'node_modules/punycode/**'
    - 'node_modules/qs/**'
    - 'node_modules/querystring/**'
    - 'node_modules/range-parser/**'
    - 'node_modules/raw-body/**'
    - 'node_modules/safe-buffer/**'
    - 'node_modules/safer-buffer/**'
    - 'node_modules/sax/**'
    - 'node_modules/send/**'
    - 'node_modules/serve-static/**'
    - 'node_modules/serverless-http/**'
    - 'node_modules/setprototypeof/**'
    - 'node_modules/statuses/**'
    - 'node_modules/toidentifier/**'
    - 'node_modules/type-is/**'
    - 'node_modules/unpipe/**'
    - 'node_modules/url/**'
    - 'node_modules/utils-merge/**'
    - 'node_modules/uuid/**'
    - 'node_modules/vary/**'
    - 'node_modules/xml2js/**'
    - 'node_modules/xmlbuilder/**'