export const addError = 'ADD_ERROR'
export const removeError = 'REMOVE_ERROR'
export const loading = 'LOADING'
export const loaded = 'LOADED'
export const getItems = 'GET_ITEMS'
export const addItem = 'ADD_ITEM'
export const signedIn = 'SIGNED_IN'
export const signedUp = 'SIGNED_UP'