/**
 * An example of how localization keys can be organized in project.
 */
export enum ValidationCode {
    VALUE_SHOULD_NOT_BE_EMPTY = 'VALUE_SHOULD_NOT_BE_EMPTY',
    VALUE_INVALID_FORMAT = 'VALUE_INVALID_FORMAT',
    VALUE_INVALID_LENGTH = 'VALUE_INVALID_LENGTH',
    VALUE_INVALID_ENUM_OPTION = 'VALUE_INVALID_ENUM_OPTION',
    ARRAY_VALUE_SHOULD_BE_AN_ARRAY = 'ARRAY_VALUE_SHOULD_BE_AN_ARRAY',
    ARRAY_AT_LEAST_ONE_ELEMENT_MUST_BE_PROVIDED = 'AT_LEAST_ONE_ELEMENT_MUST_BE_PROVIDED',
}
